version: '2'
services:
  elk-app:
    build: .
    ports:
      - "8083:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=container"
    links:
      - elk
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
